src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $summary = null;

    #[ORM\Column(length: 255)]
    private ?string $content = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'posts')]
    private Collection $tag;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publicated_at = null;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class, orphanRemoval: true, cascade: ['persist'])]
    private Collection $comments;

    public function __construct()
    {
        $this->tag = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): static
    {
        $this->summary = $summary;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImage(): string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTag(): Collection
    {
        return $this->tag;
    }

    public function addTag(Tag $tag): static
    {
        if (!$this->tag->contains($tag)) {
            $this->tag->add($tag);
        }

        return $this;
    }

    public function removeTag(Tag $tag): static
    {
        $this->tag->removeElement($tag);

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getPublicatedAt(): ?\DateTimeInterface
    {
        return $this->publicated_at;
    }

    public function setPublicatedAt(\DateTimeInterface $publicated_at): static
    {
        $this->publicated_at = $publicated_at;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use App\Entity\Tag;
use DateTime;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;


class PostType extends AbstractType
{
    /**
     * @throws \Exception
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('summary')
            ->add('content')
            ->add('publicated_at', DateTimeType::class, [
                'data' => new DateTime(timezone: new \DateTimeZone('Europe/Paris')),
                'constraints' => [
                    new GreaterThanOrEqual([
                        'value' => 'today',
                        'message' => 'La date ne peut pas être antérieure à aujourd\'hui.',
                    ]),
                ],
            ])
            ->add('image', FileType::class, [
                'label' => 'Image (JPG, PNG, GIF, etc.)',
                'mapped' => true,
                'required'=>false,
            ])
            ->add('tag', EntityType::class, [
                'class' => Tag::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Post;
use App\Entity\Tag;
use App\Entity\User;
use App\Form\EditPostType;
use App\Form\PostType;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Spipu\Html2Pdf\Html2Pdf;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\String\Slugger\SluggerInterface;





class PostController extends AbstractController
{
    #[Route('/back/post', name: 'app_post')]
    public function index(Request $request, EntityManagerInterface $entityManager, PaginatorInterface $paginator): Response
    {
        $tagEntity = $entityManager->getRepository(Tag::class);
        $allTags = $tagEntity->findAll();
        $postEntity = $entityManager->getRepository(Post::class);

        if ($request->query->get('q')) {
            $posts = $postEntity->createQueryBuilder('p')
                ->where('p.title LIKE :title')
                ->setParameter('title', '%' . $request->query->get('q') . '%')
                ->andWhere('p.user = :user')
                ->setParameter('user', $this->getUser())
                ->orderBy('p.publicated_at', 'DESC')
                ->getQuery()
                ->getResult();
        } else {
            $posts = $postEntity->createQueryBuilder('p')
                ->where('p.user = :user')
                ->setParameter('user', $this->getUser())
                ->orderBy('p.publicated_at', 'DESC')
                ->getQuery();
        }
        if($request->query->get('tag')){
            $tag = $tagEntity->findOneBy(['name' => $request->query->get('tag')]);
            foreach ($posts as $key => $post) {
                if($post->getTag()->contains($tag)){
                    continue;
                }else{
                    unset($posts[$key]);
                }
            }
        }

        $pagination = $paginator->paginate(
            $posts,
            $request->query->getInt('page', 1),
            6
        );

        return $this->render('post/index.html.twig', [
            'pagination' => $pagination,
            'tags' => $allTags,
        ]);
    }

    #[Route('/back/post/delete/{id}', name: 'app_post_delete')]
    #[IsGranted('POST_DELETE', 'post', 'Ce post n\'est pas à vous ! ')]
    public function delete(EntityManagerInterface $entityManager, Post $post): Response
    {
        $image = $post->getImage();

        try {
            if ($image) {
                if($image != "default.avif") {
                    $imageFile = $this->getParameter('brochures_directory') . '/' . $image;
                    if (file_exists($imageFile)) {
                        unlink($imageFile);
                    }
                }
            }
        } catch (FileException $e){

        }

        try {
            $entityManager->remove($post);
            $entityManager->flush();
            $this->addFlash('message', 'Le post a bien été supprimé !');
        } catch (\Exception $e) {
            $this->addFlash('error', 'Une erreur s\'est produite lors de la suppression du post : ' . $e->getMessage());
        }
        return $this->redirectToRoute('app_post');
    }

    #[Route('/post/show/{id}', name: 'app_post_show')]
    public function show(Request $request, EntityManagerInterface $entityManager, $id): Response
    {
        $postEntity = $entityManager->getRepository(Post::class);
        $post = $postEntity->find($id);
        $commentEntity = $entityManager->getRepository(Comment::class);
        $comments = $commentEntity->findBy(['post' => $post], ['publicated_at' => 'DESC']);

        if (!$post) {
            throw $this->createNotFoundException('Le post n\'existe pas.');
        }

        return $this->render('post/show.html.twig', [
            'comments' => $comments,
            'post' => $post,
        ]);
    }

    #[Route('/post/download/{id}', name: 'app_post_download')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function downloadAsPdf($id, EntityManagerInterface $entityManager): void
    {
        $html2pdf = new Html2Pdf();
        $postEntity = $entityManager->getRepository(Post::class);
        $post = $postEntity->find($id);
        $html = $this->renderView('post/dl.show.html.twig', [
            'post' => $post,
        ]);
        $html2pdf->writeHTML($html);
        $name = $post->getSlug();
        $html2pdf->output("$name.pdf");
    }

    /**
     * @throws \Exception
     */
    #[Route('/back/post/create', name: 'app_post_create')]
    public function create(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);
        $tags = $entityManager->getRepository(Tag::class)->findAll();

        if ($form->isSubmitted() && $form->isValid()) {
            $post->setCreatedAt(new \DateTimeImmutable('now', new \DateTimeZone('Europe/Paris')));
            $post->setUser($this->getUser());


            $title = $form->get('title')->getData();
            $slug = $slugger->slug($title)->lower();
            $post->setSlug($slug);

            $imageFile = $form->get('image')->getData();

            if ($imageFile === null) {
                // L'utilisateur n'a pas téléchargé d'image, utilisez l'image par défaut
                $defaultImage = 'default.avif';
                $post->setImage($defaultImage);
            } elseif ($imageFile instanceof UploadedFile) {
                // Générer un nom de fichier unique en utilisant l'horodatage et une partie aléatoire
                $newFilename = md5(uniqid()) . '.' . $imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('brochures_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // Gestion des erreurs en cas de problème lors du téléchargement
                }

                $post->setImage($newFilename);
            }

            try {
                $entityManager->persist($post);
                $entityManager->flush();

                $this->addFlash('message', 'Le post a bien été créé !');
            } catch (\Exception $e) {

                $this->addFlash('error', 'Une erreur s\'est produite lors de la création du post : ' . $e->getMessage());
            }

            return $this->redirectToRoute('app_post');
        }

        return $this->render('post/create.html.twig', [
            'form' => $form->createView(),
            'tags' => $tags,
        ]);
    }

    #[Route('/back/post/edit/{id}', name: 'app_post_edit')]
    #[IsGranted('POST_EDIT', 'post', 'Ce post n\'est pas à vous ! ')]
    public function edit(Request $request, EntityManagerInterface $entityManager, Post $post, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(EditPostType::class, $post);
        $tags = $entityManager->getRepository(Tag::class)->findAll();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $imageFile =$form->get('image')->getData();
            $previousImagePath = $post->getImage();

            $title = $form->get('title')->getData();
            $slug = $slugger->slug($title)->lower();
            $post->setSlug($slug);

            if ($imageFile instanceof UploadedFile) {
                // Générer un nom de fichier unique en utilisant l'horodatage et une partie aléatoire
                $newFilename = md5(uniqid()) . '.' . $imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('brochures_directory'),
                        $newFilename
                    );

                    if ($previousImagePath) {
                        if($previousImagePath != "default.avif") {
                            $oldImagePath = $this->getParameter('brochures_directory') . '/' . $previousImagePath;
                            if (file_exists($oldImagePath)) {
                                unlink($oldImagePath);
                            }
                        }
                    }

                } catch (FileException $e) {
                    // Gestion des erreurs en cas de problème lors du téléchargement
                }

                $post->setImage($newFilename);
            }

            try {
                $entityManager->flush();
                $this->addFlash('message', 'Le post a bien été modifié !');
            } catch (\Exception $e) {

                $this->addFlash('error', 'Une erreur s\'est produite lors de la modification du post : ' . $e->getMessage());
            }
            return $this->redirectToRoute('app_post');
        }

        return $this->render('post/editForm.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
            'tags' => $tags
        ]);
    }

    #[Route('/back/comment/delete/{id}', name: 'app_comment_delete')]
    public function deleteComment($id, EntityManagerInterface $entityManager){
        $commentRepository = $entityManager->getRepository(Comment::class);
        $comment = $commentRepository->find($id);

        if (!$comment) {
            throw $this->createNotFoundException('Le commentaire n\'existe pas.');
        }
        try {
            $entityManager->remove($comment);
            $entityManager->flush();
            $this->addFlash('message', 'Le commentaire a bien été supprimé !');
        } catch (\Exception $e) {

templates/post/_comment.html.twig
<div class="card">
    <div class="card__container">
        <a name="comment_{{ comment.id }}"></a>
        <h4 class="col-sm-4">
            <strong>{{ comment.author.username }}</strong> {{ 'commented on'|trans }}
            <strong>{{ comment.publicatedAt|format_datetime('medium', 'short', '', 'UTC') }}</strong>
        </h4>
        <div class="col-sm-7">
            <p class="card__text">{{ comment.content|markdown_to_html }}</p>
        </div>
        {% if is_granted('ROLE_ADMIN') %}
            <div class="card__fields card__fields--center">
                <a href="{{ path('app_comment_delete', { 'id': comment.id }) }}">
                    <button type="button" class="operation__button operation__button--delete">
                        {{ 'Delete' }}
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</div>

templates/post/_comment_form_error.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'comment_form_error' %}

{% block main %}
    <h1 class="text-danger">{{ 'title.comment_error'|trans }}</h1>

    <div class="jumbotron">
        {{ include('blog/_comment_form.html.twig') }}
    </div>
{% endblock %}

templates/post/_form.html.twig
{{ form_start(form, { attr: attr|default({}) }) }}

<div class="form-group">
    {{ form_label(form.title) }}
    {{ form_widget(form.title, { 'attr': {'class': 'form-control'} }) }}
    {{ form_errors(form.title) }}
</div>

<div class="form-group">
    {{ form_label(form.summary) }}
    {{ form_widget(form.summary, { 'attr': {'class': 'form-control'} }) }}
    {{ form_errors(form.summary) }}
</div>

<div class="form-group">
    {{ form_label(form.content) }}
    {{ form_widget(form.content, { 'attr': {'class': 'form-control'} }) }}
    {{ form_errors(form.content) }}
</div>


<div class="form-group">
    <div class="form__container--date">
        <legend class="col-form-label col-sm-2 col-form-label required">Publicated At</legend>
        <div class="form__date-container">
            {{ form_widget(form.publicated_at) }}
        </div>
    </div>
    {{ form_errors(form.publicated_at) }}
</div>



<div class="form-group">
    <div class="form__container--image">
        {{ form_widget(form.image, { 'attr': {'class': 'form-control-file form__image'} }) }}
    </div>
    {{ form_errors(form.image) }}
</div>


<div class="form-group form__container form__container--tag">
    {{ form_label(form.tag) }}
    {{ form_errors(form.tag) }}
    <div class="form__checkbox-container">
        {{ form_widget(form.tag) }}
    </div>
</div>

<button type="submit" class="{{ button_css|default('btn btn-primary') }}">
    <i class="fa fa-save" aria-hidden="true"></i>
    {{ button_label|default('label.create_post'|trans) }}
</button>

{{ form_end(form) }}

templates/post/_form_comment.html.twig
{{ form_start(form, {method: 'POST', action: path('app_add_comment', {'postId':post.id})}) }}


<fieldset>
    <legend>
        <i class="fa fa-comment" aria-hidden="true"></i> {{ 'Add comment'|trans }}
    </legend>
    {{ form_errors(form) }}

    <div class="form-group comment-form {% if not form.content.vars.valid %}has-error{% endif %}">
        {{ form_label(form.content, 'label.content', {label_attr: {class: 'sr-only'}}) }}
        {{ form_errors(form.content) }}

        {{ form_widget(form.content, {attr: {rows: 10}}) }}
        {{ form_help(form.content) }}
    </div>

    <div class="form-group">
        <button class="btn btn-primary float-right" type="submit">
            <i class="fa fa-paper-plane" aria-hidden="true"></i> {{ 'Publish comment'|trans }}
        </button>
    </div>
</fieldset>
{{ form_end(form) }}

templates/post/_post.html.twig
<div class="card">
    <div class="card__container">
        <a href="{{ path('app_post_show', {'id': post.id}) }}">
            <img src="{{ asset('uploads/images/' ~ post.image) }}" alt="post_image" class="card__image">
        </a>
        <div class="card__content">
            <div class="card__fields">
                <a href="{{ path('app_post_show', {'id': post.id}) }}" class="card__hypertext">{{ post.title }}</a>
                <div class="card__publish-info">
                    <p class="card__date"><i class="fa fa-calendar"></i> {{ post.getPublicatedAt()|format_datetime('long', 'medium', '', 'Europe/Paris') }}</p>
                    <p class="card__date"><i class="fa fa-user"></i> {{ post.user.username }}</p>
                </div>
                <p class="card__text">{{ post.summary }}</p>
            </div>

            {% if admin %}
                <div class="card__operations">
                    <a href="{{ path('app_post_edit', {'id': post.id}) }}" class="card__hypertext--underline_off">
                        <button type="button" class="operation__button operation__button--edit">
                            Editer
                        </button>
                    </a>

                    <a href="{{ path('app_post_delete', {'id': post.id}) }}">
                        <button type="button" class="operation__button operation__button--delete">
                            Supprimer
                        </button>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</div>

templates/post/_search_form.html.twig
<form action="{{ path(target) }}" class="form">
    <div class="form__container">
        <input
                type="search"
                name="q"
                class="form-control form__input--margin"
                placeholder="{{ 'Search title'|trans }}..."
                aria-label="{{ 'Search'|trans }}"
        >
        <label for="tag" style="display: none">Tag</label>
        <select name="tag" class="form-control ">
            <option selected disabled>{{ 'Search tag'|trans }}...</option>
            {% for tag in tags %}
                <option value="{{ tag.name }}">{{ tag.name }}</option>
            {% endfor %}
        </select>
    </div>
    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i>{{ 'Search'|trans }}</button>
</form>

templates/post/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create{% endblock %}

{% block body %}
    <h1>Create</h1>
    {{ include('post/_form.html.twig',{
        form:form,
        'button_label':'create'|trans,
    }, with_context =  false) }}
{% endblock %}

templates/post/dl.show.html.twig
{% extends 'base.html.twig' %}
{% block header %} {% endblock %}
{% block body %}

    <div class="post" style="margin:0 5rem">
        <h1>{{ post.title }}</h1>

        <p class="post-metadata">
            <span class="metadata"><i class="fa fa-calendar"></i> {{ post.publicatedAt|format_datetime('long', 'medium', '', 'UTC') }}</span>
            <span class="metadata"><i class="fa fa-user"></i> {{ post.user.username }}</span>
        </p>


        <img src="https://picsum.photos/seed/{{ post.slug }}/200/300" alt="" style="float:left;padding-right:2rem">
        <div class="content" style="text-align: justify">
            {{ post.content|markdown_to_html }}
        </div>
    </div>
{% endblock %}

templates/post/editForm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit{% endblock %}

{% block body %}
    <h1>Edit</h1>
        {{ include('post/_form.html.twig', {
            form: form,
            'button_label': 'edit'|trans,
        }, with_context = false) }}
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des posts{% endblock %}

{% block body %}

    <div class="post-list-wrapper">
        {% for message in app.flashes('message') %}
            <div class="alert success" id="message_{{ loop.index }}">{{ message }}<a href="#" class="close" onclick="closeMessage({{ loop.index }})">&times;</a></div>
        {% endfor %}

        {% for message in app.flashes('error') %}
            <div class="alert error" id="error_{{ loop.index }}">{{ message }}<a href="#" class="close" onclick="closeMessage({{ loop.index }})">&times;</a></div>
        {% endfor %}


        <div class="post-list-header">
            <h1>Liste de vos posts:</h1>
            <a href="{{ path('app_post_create') }}" class="operation__button operation__button--edit operation__button--create">
                Create
            </a>
        </div>
        {{ include( 'post/_search_form.html.twig', {target:'app_post'})}}
        <div class="container cards_container" style="margin-left:-15px">
            {% if pagination|length > 0 %}
                {% for post in pagination %}
                    {{ include("post/_post.html.twig", {admin: true}) }}
                {% endfor %}
            {% else %}
                <div class="my-md-4">
                    <div class="alert alert-info">
                        No post found
                    </div>
                </div>
            {% endif %}
        </div>

        <!-- Afficher la pagination -->
        <div class="pagination">
            {{ knp_pagination_render(pagination) }}
        </div>
    </div>

{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Post detail'|trans }}{% endblock %}
{% block body %}
{% for message in app.flashes('message') %}
    <div class="alert alert--home success" id="message_{{ loop.index }}">{{ message }}<a href="#" class="close" onclick="closeMessage({{ loop.index }})">&times;</a></div>
{% endfor %}

{% for message in app.flashes('error') %}
    <div class="alert alert--home error" id="error_{{ loop.index }}">{{ message }}<a href="#" class="close" onclick="closeMessage({{ loop.index }})">&times;</a></div>
{% endfor %}
    <article class="post" style="margin:0 5rem; min-height: 400px">
        <h1>{{ post.title }}</h1>

        <p class="post-metadata">
            <span class="metadata"><i class="fa fa-calendar"></i> {{ post.publicatedAt|format_datetime('long', 'medium', '', 'UTC') }}</span>
            <span class="metadata"><i class="fa fa-user"></i> {{ post.user.username }}</span>
        </p>
        {% for tag in post.tag %}
            <span class="badge badge-primary">{{ tag.name }}</span>
        {% endfor %}


        <img src="{{ asset('uploads/images/' ~ post.image) }}" alt="post_image" class="card__image--detail" style="float:left;padding-right:2rem">
        <div class="content" style="text-align: justify">
        {{ post.content|markdown_to_html }}
        </div>
        {% if app.user %}
        <div class="clearfix"></div>
        <a href="{{ path("app_post_download", {'id': post.id}) }}" target="_blank">
            <button type="button" class="download__button">
                <i class="fa fa-download"></i>
                {{ 'Download as pdf'|trans }}
            </button>
        </a>
        {% endif %}
    </article>



    <div class="comments" style="display:inline-block">
        <h3>
            <i class="fa fa-comments" aria-hidden="true"></i> {{  post.comments|length }} {{ 'Comments'|trans }}
        </h3>
        {% if app.user %}
        <div class="post-comment">
            {{ render(controller('App\\Controller\\HomeController::commentForm', {'post':post})) }}
        </div>
    {% else %}
        <div class="post-comment">
            <p>{{ 'You must be logged in to comment'|trans }}</p>
            {% endif %}
        </div>

        <div class="cards_container" style="margin-bottom:40px">
        {% for comment in comments %}
            {{ include('post/_comment.html.twig') }}
        {% else %}
            <div class="post-comment">
                <p>{{ 'No comments'|trans }}</p>
            </div>
        {% endfor %}
        </div>
    </div>

{% endblock %}